import { useEffect, useRef, useCallback, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { useGameStore, useSimulationStore } from '@shared/stores'
import { playSfx, stopMusic } from '@shared/useAudioManager'
import { computeBadges, computeCompositeGrade, GRADE_COLORS, badgeIdsFromBadges } from '@shared/badgeUtils'
import styles from './VictoryScreen.module.css'

export function VictoryScreen() {
  const navigate = useNavigate()
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    stopMusic()
    playSfx('victory')
  }, [])

  const sigma = useGameStore((s) => s.sigma)
  const r0 = useGameStore((s) => s.r0)
  const budget = useGameStore((s) => s.budget)
  const completedCases = useGameStore((s) => s.completedCases)
  const caseResults = useGameStore((s) => s.caseResults)
  const appliedInterventions = useGameStore((s) => s.appliedInterventions)
  const setEarnedBadges = useGameStore((s) => s.setEarnedBadges)
  const earnedBadges = useGameStore((s) => s.earnedBadges)
  const reset = useGameStore((s) => s.reset)
  const tick = useSimulationStore((s) => s.tick)

  const compositeGrade = computeCompositeGrade(caseResults, completedCases)
  const badges = useMemo(() => computeBadges(caseResults, appliedInterventions, completedCases), [caseResults, appliedInterventions, completedCases])
  const gradeColor = GRADE_COLORS[compositeGrade] ?? '#e74c3c'

  useEffect(() => {
    if (badges.length > 0) {
      const ids = badgeIdsFromBadges(badges)
      const existing = earnedBadges
      const merged = [...new Set([...existing, ...ids])]
      if (merged.length > existing.length || ids.length !== existing.length) {
        setEarnedBadges(merged)
      }
    }
  }, [badges, earnedBadges, setEarnedBadges])

  const handlePlayAgain = () => {
    reset()
    navigate('/', { replace: true })
  }

  const handleContinue = () => {
    navigate('/strategy', { replace: true })
  }

  const handleShare = useCallback(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    canvas.width = 400
    canvas.height = 500

    ctx.fillStyle = '#1a1a2e'
    ctx.fillRect(0, 0, 400, 500)

    ctx.fillStyle = '#f39c12'
    ctx.font = 'bold 24px monospace'
    ctx.textAlign = 'center'
    ctx.fillText('GIHA — Scorecard', 200, 40)

    ctx.fillStyle = '#2ecc71'
    ctx.font = '48px monospace'
    ctx.fillText(`Grade ${compositeGrade}`, 200, 100)

    ctx.font = '14px monospace'
    ctx.fillStyle = '#ccc'
    ctx.fillText(`Media Literacy: ${sigma}`, 200, 145)
    ctx.fillText(`Spread Rate: ${r0.toFixed(2)}`, 200, 168)
    ctx.fillText(`Budget: ${budget}`, 200, 191)
    ctx.fillText(`Cases Solved: ${completedCases}/3`, 200, 214)
    ctx.fillText(`Interventions Deployed: ${appliedInterventions.length}`, 200, 237)
    ctx.fillText(`Ticks Survived: ${tick}`, 200, 260)

    ctx.fillStyle = '#888'
    ctx.font = '12px monospace'
    ctx.fillText(`Achievements: ${badges.map((b) => b.name).join(', ') || 'None'}`, 200, 300)

    ctx.fillStyle = '#555'
    ctx.font = '10px monospace'
    ctx.fillText('Generated by GIHA — Hackathon 2026', 200, 460)

    const link = document.createElement('a')
    link.download = 'giha-scorecard.png'
    link.href = canvas.toDataURL('image/png')
    link.click()
  }, [sigma, r0, budget, completedCases, appliedInterventions.length, tick, badges, compositeGrade])

  return (
    <div className={styles.screen} data-testid="victory-screen">
      <canvas ref={canvasRef} style={{ display: 'none' }} />

      <div className={styles.animatedBg} />

      <div className={styles.badge}>MISSION COMPLETE</div>

      <div className={styles.gradeCircle} style={{ borderColor: gradeColor, color: gradeColor }}>
        <div className={styles.gradeLetter}>{compositeGrade}</div>
        <div className={styles.gradeLabel}>Composite Grade</div>
      </div>

      <p className={styles.subtitle}>
        {sigma >= 80 && r0 < 0.8
          ? 'Veritas is stable. The Shadow Collective\'s network has been exposed. The city will recover — not because disinfo was eliminated, but because its citizens learned to question, verify, and think critically.'
          : 'Veritas survived, but the city remains fragile. The Shadow Collective retreated, not because they were defeated, but because their operation was exposed. True resilience takes time.'}
      </p>

      <div className={styles.statsGrid}>
        <div className={styles.stat}>
          <span className={styles.statValue}>{sigma}</span>
          <span className={styles.statLabel}>Media Literacy</span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statValue}>{r0.toFixed(2)}</span>
          <span className={styles.statLabel}>Spread Rate</span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statValue}>{completedCases}/3</span>
          <span className={styles.statLabel}>Cases Solved</span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statValue}>{budget}</span>
          <span className={styles.statLabel}>Budget</span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statValue}>{appliedInterventions.length}</span>
          <span className={styles.statLabel}>Interventions</span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statValue}>{tick}</span>
          <span className={styles.statLabel}>Ticks</span>
        </div>
      </div>

      {badges.length > 0 && (
        <div className={styles.badges} data-testid="achievement-badges">
          <div className={styles.badgesHeader}>Achievements</div>
          <div className={styles.badgesRow}>
            {badges.map((badge) => (
              <div key={badge.id} className={styles.badgeItem} data-testid={`badge-${badge.id}`}>
                <span className={styles.badgeIcon}>{badge.icon}</span>
                <span className={styles.badgeName}>{badge.name}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className={styles.lessons}>
        <div className={styles.lessonsHeader}>MIL Lessons Applied</div>
        <ul className={styles.lessonsList}>
          <li>Always verify evidence through multiple independent analyses</li>
          <li>Metadata and timestamps reveal manipulation history</li>
          <li>Cross-referencing sources detects coordinated disinformation</li>
        </ul>
      </div>

      <div className={styles.actionsRow}>
        <button
          className={styles.shareBtn}
          onClick={handleShare}
          data-testid="share-btn"
        >
          Share Scorecard
        </button>
        <button
          className={styles.continueBtn}
          onClick={handleContinue}
          data-testid="continue-btn"
        >
          Continue Playing
        </button>
        <button
          className={styles.playAgainBtn}
          onClick={handlePlayAgain}
          data-testid="play-again-btn"
        >
          Play Again
        </button>
      </div>
    </div>
  )
}
