import * as TUNING from './tuning'

export { TUNING }
export {
  SIGMA_BOUNDS,
  R0_BOUNDS,
  POPULATION_INITIAL,
  POPULATION_FRACTIONS,
  STARTING_STATE,
  ODE_PARAMS,
  SIGMA_DYNAMICS,
  R0_MITIGATION,
  PHASE_THRESHOLDS,
  SIGMA_TRAP,
  WIN_CONDITIONS,
  LOSS_CONDITIONS,
  INCOME,
  INTERVENTION_DEFAULTS,
  EFFECTIVENESS_BUFF,
  CASE_BUDGET_BONUSES,
  UPGRADED_EMERGENCY,
  CASE_UNLOCK,
  DETECTIVE_SCORING,
  DETECTIVE_OUTCOME,
  CASE_DIFFICULTY,
  WARNINGS,
} from './tuning'

export const RECOVERY_RATE = TUNING.ODE_PARAMS.RECOVERY_RATE
export const INCUBATION_RATE = TUNING.ODE_PARAMS.INCUBATION_RATE
export const SIGMA_DECAY_COEFFICIENT = TUNING.ODE_PARAMS.SIGMA_DECAY_COEFFICIENT
export const SIGMA_MIN = TUNING.SIGMA_BOUNDS.MIN
export const SIGMA_MAX = TUNING.SIGMA_BOUNDS.MAX
export const R0_MIN = TUNING.R0_BOUNDS.MIN
export const R0_MAX = TUNING.R0_BOUNDS.MAX
export const R0_NOISE_AMPLITUDE = TUNING.R0_MITIGATION.NOISE_AMPLITUDE
export const LITERACY_MITIGATION_FACTOR = TUNING.R0_MITIGATION.LITERACY_FACTOR
export const FACTCHECK_MITIGATION_FACTOR = TUNING.R0_MITIGATION.FACTCHECK_FACTOR
export const AUDIT_MITIGATION_FACTOR = TUNING.R0_MITIGATION.AUDIT_FACTOR
export const TRAP_SIGMA_THRESHOLD = TUNING.PHASE_THRESHOLDS.TRAP_SIGMA
export const CRISIS_SIGMA_THRESHOLD = TUNING.PHASE_THRESHOLDS.CRISIS_SIGMA
export const CRISIS_R0_THRESHOLD = TUNING.PHASE_THRESHOLDS.CRISIS_R0
export const OUTBREAK_SIGMA_THRESHOLD = TUNING.PHASE_THRESHOLDS.OUTBREAK_SIGMA
export const OUTBREAK_R0_THRESHOLD = TUNING.PHASE_THRESHOLDS.OUTBREAK_R0
export const CALM_SIGMA_THRESHOLD = TUNING.PHASE_THRESHOLDS.CALM_SIGMA
export const CALM_R0_THRESHOLD = TUNING.PHASE_THRESHOLDS.CALM_R0
export const TRAP_CONSECUTIVE_TICKS = TUNING.SIGMA_TRAP.CONSECUTIVE_TICKS
export const INITIAL_EXPOSED_FRACTION = TUNING.POPULATION_FRACTIONS.INITIAL_EXPOSED
export const INITIAL_INFECTED_FRACTION = TUNING.POPULATION_FRACTIONS.INITIAL_INFECTED
