export { simulateTick } from './simulate'
export type { SimulationParams } from './simulate'
export { computeR0 } from './r0'
export { computeSigma } from './sigma'
export { detectSigmaTrap } from './sigma-trap'
export { classifyPhase } from './phase-classifier'
export { getDistrict, DISTRICTS, computeDistrictEffectiveR0 } from './districts'
export { getIntervention, INTERVENTIONS, INTERVENTION_COLORS } from './interventions'
export { createActiveEffect, tickActiveEffects } from './active-effects'

export type { PopulationState } from './types'
export type { District } from './types'
export type { Phase } from './types'
export type { ActiveEffect } from './types'
export type { SimulationConfig } from './types'
export type { SimulationSnapshot } from './types'
export type { Intervention } from './interventions'
export type { InterventionEffect } from './interventions'
